In [1]:
# Basic packages always been used
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Data preprocessing useful function
from sklearn.preprocessing import LabelEncoder

# Data scaling
# normalization
from sklearn.preprocessing import MinMaxScaler

# standardization
from sklearn.preprocessing import StandardScaler

# Function for spilting training & testing data set
from sklearn.model_selection import train_test_split

# Algorithm
from sklearn.linear_model import LogisticRegression

# Function for hyper-parameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

# Functions for evaluation
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from imblearn.metrics import sensitivity_score
from imblearn.metrics import specificity_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import plot_roc_curve, roc_auc_score, roc_curve

# 3. Data scaling with minimax technique

In [2]:
#load data(sometimes need to use "/")
dummied_new_df = pd.read_csv('C:/Users/user/Desktop/Final_assignment/Data/中風_deleteNA_dummies.csv')
dummied_new_df

X2      X8    X9  X1_1  X1_2  X3_0  X3_1  X4_0  X4_1  X5_0  ...  X6_3  \
0     67  228.69  36.6     1     0     1     0     0     1     0  ...     1   
1     80  105.92  32.5     1     0     1     0     0     1     0  ...     1   
2     49  171.23  34.4     0     1     1     0     1     0     0  ...     1   
3     79  174.12  24.0     0     1     0     1     1     0     0  ...     0   
4     81  186.21  29.0     1     0     1     0     1     0     0  ...     1   
...   ..     ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3420  82   71.97  28.3     1     0     0     1     1     0     0  ...     0   
3421  57   77.93  21.7     0     1     1     0     1     0     0  ...     1   
3422  81  125.20  40.0     0     1     1     0     1     0     0  ...     0   
3423  35   82.99  30.6     0     1     1     0     1     0     0  ...     0   
3424  51  166.29  25.6     1     0     1     0     1     0     0  ...     1   

      X6_4  X6_5  X7_1  X7_2  X10_1  X10_2  X10_3  Y_0  Y_1  
0        0     0     0     1      0      1      0    0    1  
1        0     0     1     0      1      0      0    0    1  
2        0     0     0     1      0      0      1    0    1  
3        1     0     1     0      1      0      0    0    1  
4        0     0     0     1      0      1      0    0    1  
...    ...   ...   ...   ...    ...    ...    ...  ...  ...  
3420     1     0     1     0      1      0      0    1    0  
3421     0     0     1     0      1      0      0    1    0  
3422     1     0     0     1      1      0      0    1    0  
3423     1     0     1     0      1      0      0    1    0  
3424     0     0     1     0      0      1      0    1    0  

[3425 rows x 23 columns]

In [3]:
#minimax scaling
MMscaler=MinMaxScaler(feature_range=(0, 1))
scaling=MMscaler.fit_transform(dummied_new_df)
scaled_data=pd.DataFrame(data=scaling)
scaled_data.columns=['X2','X8','X9','X1_1','X1_2','X3_0','X3_1','X4_0','X4_1','X5_0','X5_1','X6_1','X6_2','X6_3','X6_4','X6_5','X7_1','X7_2','X10_1','X10_2','X10_3','Y_0','Y_1'
]
scaled_data.head()

X2        X8        X9  X1_1  X1_2  X3_0  X3_1  X4_0  X4_1  X5_0  \
0  0.791667  0.801265  0.311801   1.0   0.0   1.0   0.0   0.0   1.0   0.0   
1  0.972222  0.234512  0.260870   1.0   0.0   1.0   0.0   0.0   1.0   0.0   
2  0.541667  0.536008  0.284472   0.0   1.0   1.0   0.0   1.0   0.0   0.0   
3  0.958333  0.549349  0.155280   0.0   1.0   0.0   1.0   1.0   0.0   0.0   
4  0.986111  0.605161  0.217391   1.0   0.0   1.0   0.0   1.0   0.0   0.0   

   ...  X6_3  X6_4  X6_5  X7_1  X7_2  X10_1  X10_2  X10_3  Y_0  Y_1  
0  ...   1.0   0.0   0.0   0.0   1.0    0.0    1.0    0.0  0.0  1.0  
1  ...   1.0   0.0   0.0   1.0   0.0    1.0    0.0    0.0  0.0  1.0  
2  ...   1.0   0.0   0.0   0.0   1.0    0.0    0.0    1.0  0.0  1.0  
3  ...   0.0   1.0   0.0   1.0   0.0    1.0    0.0    0.0  0.0  1.0  
4  ...   1.0   0.0   0.0   0.0   1.0    0.0    1.0    0.0  0.0  1.0  

[5 rows x 23 columns]

# 4. Set dependent variable(Y or target) & independent variable(X)

In [7]:
#set x (make prediction) with minimax
scaled_x=scaled_data.drop(['Y_0','Y_1'],axis=1).copy()
#set y (want to predict)
scaled_y=scaled_data['Y_1'].copy()
scaled_y=scaled_y.astype(int)

# 5.  Hyper parameter tuning

In [12]:
accuracy_all_list=[]
precision_all_list=[]
sensitivity_all_list=[]
specificity_all_list=[]
f1score_all_list=[]
auc_all_list=[]

for i in range(1,11):
    
    #Split the data (split into 80% training data & 20% testing data) (lock seed) 
    x_train,x_test,y_train,y_test=train_test_split(scaled_x,scaled_y,test_size=0.2,random_state=i)

    # Initializing Classifiers
    clf1 = LogisticRegression(penalty='l1',solver='liblinear',random_state=4)


    # Setting up the parameter grids
    param_grid1 = [{'C': list(range(0, 11)) + [None]}]

    # K fold cross-validation
    cross_val=KFold(n_splits=5,shuffle=True,random_state=4)
    
    # using gridsearch for hyper-parameter tuning
    gridS_model = GridSearchCV(estimator=clf1,
                                param_grid=param_grid1,
                                scoring='roc_auc',
                                n_jobs=-1,
                                cv=cross_val,
                                verbose=0,
                                refit=True)

    #peforming gridsearch & save each models training result
    gridS_model.fit(x_train, y_train) 
    training_score=gridS_model.best_score_  
    best_parameter=gridS_model.best_params_
    train_model=gridS_model.best_estimator_
    
    
    #print training result
    print('Round',i)
    print('random_state=',i)
    print('Training score:',training_score)
    print('Best Hyper-parameter set:',best_parameter)
    
    # Get model perdiction
    proba=train_model.predict_proba(x_test)[:, 1]
    auc_value = roc_auc_score(y_test, proba)
    fpr, tpr, thresholds = roc_curve(y_test, proba, pos_label=1)
    #caculate Youden's J statistic
    J_score=tpr-fpr
    best_JTH_cutpoint_index=np.argmax(J_score)
    best_JS_threshold=thresholds[best_JTH_cutpoint_index]

    # Calculate performance
    final_prediction=(proba >= best_JS_threshold).astype('int')
    confusion = confusion_matrix(y_test,final_prediction)
    TP=confusion[1,1]
    TN=confusion[0,0]
    FP=confusion[0,1]
    FN=confusion[1,0]
    accuracy=(TP+TN)/(TP+TN+FP+FN)
    sensitivity = TP/(TP+FN)
    specificity = TN/(FP+TN)
    precision=TP/(TP+FP)
    f1score=2*(precision*sensitivity)/(precision+sensitivity)
    

    #print results
    print('Testing results with best threshold')
    print('===================================')
    print('Accuracy:   ',round(accuracy,3))
    print('Precision:  ',round(precision,3))
    print('Sensitivity:',round(sensitivity,3))
    print('Specificity:',round(specificity,3))
    print('F1 score:   ',round(f1score,3))
    print('AUC:        ',round(auc_value,3))
    print('ThresHold:  ',best_JS_threshold)
    print('-----------------------------------')
    print(confusion)
    print('---------------------------------------')
    print('---------------------------------------\n\n')
    
#     #plot ROC fig with exist package module
#     roc_fig=plot_roc_curve(train_model, x_test, y_test)
    
    
    
    accuracy_all=[round(accuracy,3)]
    for a in accuracy_all:
        accuracy_all_list+=[a]
        
    precision_all=[round(precision,3)]
    for a in precision_all:
        precision_all_list+=[a]
    
    sensitivity_all=[round(sensitivity,3)]
    for a in sensitivity_all:
        sensitivity_all_list+=[a]
        
    specificity_all=[round(specificity,3)]
    for a in specificity_all:
        specificity_all_list+=[a]
        
    f1score_all=[round(f1score,3)]
    for a in f1score_all:
        f1score_all_list+=[a]
        
    auc_all=[round(auc_value,3)]
    for a in auc_all:
        auc_all_list+=[a]


best_Accuracy=max(accuracy_all_list)
best_round=accuracy_all_list.index(best_Accuracy)+1
print('Best:',best_Accuracy)
print('Best Round:',best_round)
print('---------------------------------------')
print('Accuracy_mean:',round(np.mean(accuracy_all_list),3),',Accuracy_std:',round(np.std(accuracy_all_list),2))
print('Precision_mean:',round(np.mean(precision_all_list),3),',Precision_std:',round(np.std(precision_all_list),2))
print('Sensitivity_mean:',round(np.mean(sensitivity_all_list),3),',Sensitivity_std:',round(np.std(sensitivity_all_list),2))
print('Specificity_mean:',round(np.mean(specificity_all_list),3),',Specificity_std:',round(np.std(specificity_all_list),2))
print('F1 score_mean:',round(np.mean(f1score_all_list),3),',F1 score_std:',round(np.std(f1score_all_list),2))
print('AUC_mean:',round(np.mean(auc_all_list),3),',AUC_std:',round(np.std(auc_all_list),2))


C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 1
random_state= 1
Training score: 0.8038594594030289
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.758
Precision:   0.163
Sensitivity: 0.941
Specificity: 0.748
F1 score:    0.278
AUC:         0.9
ThresHold:   0.059632443379063316
-----------------------------------
[[487 164]
 [  2  32]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 2
random_state= 2
Training score: 0.8199542802581501
Best Hyper-parameter set: {'C': 3}
Testing results with best threshold
Accuracy:    0.777
Precision:   0.192
Sensitivity: 0.773
Specificity: 0.777
F1 score:    0.308
AUC:         0.833
ThresHold:   0.05612310510206977
-----------------------------------
[[498 143]
 [ 10  34]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 3
random_state= 3
Training score: 0.8315795967640751
Best Hyper-parameter set: {'C': 10}
Testing results with best threshold
Accuracy:    0.712
Precision:   0.12
Sensitivity: 0.788
Specificity: 0.709
F1 score:    0.209
AUC:         0.789
ThresHold:   0.05749952369655645
-----------------------------------
[[462 190]
 [  7  26]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 4
random_state= 4
Training score: 0.8325271670945655
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.628
Precision:   0.106
Sensitivity: 0.909
Specificity: 0.613
F1 score:    0.19
AUC:         0.794
ThresHold:   0.0337069957608293
-----------------------------------
[[400 252]
 [  3  30]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 5
random_state= 5
Training score: 0.8262237553742127
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.747
Precision:   0.145
Sensitivity: 0.778
Specificity: 0.746
F1 score:    0.245
AUC:         0.791
ThresHold:   0.056267829517054425
-----------------------------------
[[484 165]
 [  8  28]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 6
random_state= 6
Training score: 0.8236398766185202
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.666
Precision:   0.146
Sensitivity: 0.864
Specificity: 0.652
F1 score:    0.249
AUC:         0.814
ThresHold:   0.03248643434207559
-----------------------------------
[[418 223]
 [  6  38]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 7
random_state= 7
Training score: 0.8183872390199503
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.831
Precision:   0.16
Sensitivity: 0.778
Specificity: 0.833
F1 score:    0.266
AUC:         0.848
ThresHold:   0.11301048451997416
-----------------------------------
[[548 110]
 [  6  21]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 8
random_state= 8
Training score: 0.8250003710902567
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.689
Precision:   0.13
Sensitivity: 0.861
Specificity: 0.68
F1 score:    0.225
AUC:         0.806
ThresHold:   0.04442023177683714
-----------------------------------
[[441 208]
 [  5  31]]
---------------------------------------
---------------------------------------




C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

Round 9
random_state= 9
Training score: 0.8246546126834055
Best Hyper-parameter set: {'C': 7}
Testing results with best threshold
Accuracy:    0.631
Precision:   0.113
Sensitivity: 0.914
Specificity: 0.615
F1 score:    0.202
AUC:         0.819
ThresHold:   0.03178267379364426
-----------------------------------
[[400 250]
 [  3  32]]
---------------------------------------
---------------------------------------


Round 10
random_state= 10
Training score: 0.8322878429561152
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.726
Precision:   0.144
Sensitivity: 0.75
Specificity: 0.724
F1 score:    0.242
AUC:         0.788
ThresHold:   0.05826891266035165
-----------------------------------
[[467 178]
 [ 10  30]]
---------------------------------------
---------------------------------------


Best: 0.831
Best Round: 7
---------------------------------------
Accuracy_mean: 0.716 ,Accuracy_std: 0.06
Precision_mean: 0.142 ,Precision_std: 0.02
Sensitivity_m

C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1528, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
 

In [9]:
x_train,x_test,y_train,y_test=train_test_split(scaled_x,scaled_y,test_size=0.2,random_state=7)
model=LogisticRegression(penalty='l1',solver='liblinear',C=1,random_state=4)
model.fit(x_train,y_train)

LogisticRegression(C=1, penalty='l1', random_state=4, solver='liblinear')

In [11]:
importance=model.coef_[0]
importance_sort = np.argsort(importance)[::-1]
df_col = dummied_new_df.columns[0:]
print('Feature Importance')
print('----------------------------------------------')
for i,v in enumerate(importance):
    df_columns=df_col[i]
    print('%s \t  Feature_Imp= %.5f' % (df_columns,v))
print('\n')    
print('Feature ranking')
print('----------------------------------------------')
    
# 依序迭代出重要特徵
for f in range(x_train.shape[1]):
    print(f"{f+1:>2d}) {df_col[importance_sort[f]]:<30s} {importance[importance_sort[f]]:.3f}")

Feature Importance
----------------------------------------------
X2 	  Feature_Imp= 4.85768
X8 	  Feature_Imp= 0.72156
X9 	  Feature_Imp= 0.00000
X1_1 	  Feature_Imp= -0.15472
X1_2 	  Feature_Imp= 0.00000
X3_0 	  Feature_Imp= -0.51649
X3_1 	  Feature_Imp= 0.00000
X4_0 	  Feature_Imp= -0.51339
X4_1 	  Feature_Imp= 0.00000
X5_0 	  Feature_Imp= 0.00000
X5_1 	  Feature_Imp= -0.11714
X6_1 	  Feature_Imp= 0.00000
X6_2 	  Feature_Imp= 0.00000
X6_3 	  Feature_Imp= 0.14132
X6_4 	  Feature_Imp= -0.12770
X6_5 	  Feature_Imp= 0.00000
X7_1 	  Feature_Imp= 0.00000
X7_2 	  Feature_Imp= -0.00515
X10_1 	  Feature_Imp= -0.31461
X10_2 	  Feature_Imp= -0.25167
X10_3 	  Feature_Imp= 0.00000


Feature ranking
----------------------------------------------
 1) X2                             4.858
 2) X8                             0.722
 3) X6_3                           0.141
 4) X6_1                           0.000
 5) X9                             0.000
 6) X1_2                           0.000
 7) X3_1 