In [1]:
# Basic packages always been used
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Data preprocessing useful function
from sklearn.preprocessing import LabelEncoder

# Data scaling
# normalization
from sklearn.preprocessing import MinMaxScaler

# standardization
from sklearn.preprocessing import StandardScaler

# Function for spilting training & testing data set
from sklearn.model_selection import train_test_split

# Algorithm
from sklearn.svm import LinearSVC

# Function for hyper-parameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

# Functions for evaluation
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from imblearn.metrics import sensitivity_score
from imblearn.metrics import specificity_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import plot_roc_curve, roc_auc_score, roc_curve

# 3. Data scaling with minimax technique

In [2]:
#load data(sometimes need to use "/")
dummied_new_df = pd.read_csv('C:/Users/user/Desktop/Final_assignment/Data/中風_deleteNA_dummies.csv')
dummied_new_df

X2      X8    X9  X1_1  X1_2  X3_0  X3_1  X4_0  X4_1  X5_0  ...  X6_3  \
0     67  228.69  36.6     1     0     1     0     0     1     0  ...     1   
1     80  105.92  32.5     1     0     1     0     0     1     0  ...     1   
2     49  171.23  34.4     0     1     1     0     1     0     0  ...     1   
3     79  174.12  24.0     0     1     0     1     1     0     0  ...     0   
4     81  186.21  29.0     1     0     1     0     1     0     0  ...     1   
...   ..     ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3420  82   71.97  28.3     1     0     0     1     1     0     0  ...     0   
3421  57   77.93  21.7     0     1     1     0     1     0     0  ...     1   
3422  81  125.20  40.0     0     1     1     0     1     0     0  ...     0   
3423  35   82.99  30.6     0     1     1     0     1     0     0  ...     0   
3424  51  166.29  25.6     1     0     1     0     1     0     0  ...     1   

      X6_4  X6_5  X7_1  X7_2  X10_1  X10_2  X10_3  Y_0  Y_1  
0        0     0     0     1      0      1      0    0    1  
1        0     0     1     0      1      0      0    0    1  
2        0     0     0     1      0      0      1    0    1  
3        1     0     1     0      1      0      0    0    1  
4        0     0     0     1      0      1      0    0    1  
...    ...   ...   ...   ...    ...    ...    ...  ...  ...  
3420     1     0     1     0      1      0      0    1    0  
3421     0     0     1     0      1      0      0    1    0  
3422     1     0     0     1      1      0      0    1    0  
3423     1     0     1     0      1      0      0    1    0  
3424     0     0     1     0      0      1      0    1    0  

[3425 rows x 23 columns]

In [3]:
#minimax scaling
MMscaler=MinMaxScaler(feature_range=(0, 1))
scaling=MMscaler.fit_transform(dummied_new_df)
scaled_data=pd.DataFrame(data=scaling)
scaled_data.columns=['X2','X8','X9','X1_1','X1_2','X3_0','X3_1','X4_0','X4_1','X5_0','X5_1','X6_1','X6_2','X6_3','X6_4','X6_5','X7_1','X7_2','X10_1','X10_2','X10_3','Y_0','Y_1'
]
scaled_data.head()

X2        X8        X9  X1_1  X1_2  X3_0  X3_1  X4_0  X4_1  X5_0  \
0  0.791667  0.801265  0.311801   1.0   0.0   1.0   0.0   0.0   1.0   0.0   
1  0.972222  0.234512  0.260870   1.0   0.0   1.0   0.0   0.0   1.0   0.0   
2  0.541667  0.536008  0.284472   0.0   1.0   1.0   0.0   1.0   0.0   0.0   
3  0.958333  0.549349  0.155280   0.0   1.0   0.0   1.0   1.0   0.0   0.0   
4  0.986111  0.605161  0.217391   1.0   0.0   1.0   0.0   1.0   0.0   0.0   

   ...  X6_3  X6_4  X6_5  X7_1  X7_2  X10_1  X10_2  X10_3  Y_0  Y_1  
0  ...   1.0   0.0   0.0   0.0   1.0    0.0    1.0    0.0  0.0  1.0  
1  ...   1.0   0.0   0.0   1.0   0.0    1.0    0.0    0.0  0.0  1.0  
2  ...   1.0   0.0   0.0   0.0   1.0    0.0    0.0    1.0  0.0  1.0  
3  ...   0.0   1.0   0.0   1.0   0.0    1.0    0.0    0.0  0.0  1.0  
4  ...   1.0   0.0   0.0   0.0   1.0    0.0    1.0    0.0  0.0  1.0  

[5 rows x 23 columns]

# 4. Set dependent variable(Y or target) & independent variable(X)

In [7]:
#set x (make prediction) with minimax
scaled_x=scaled_data.drop(['Y_0','Y_1'],axis=1).copy()
#set y (want to predict)
scaled_y=scaled_data['Y_1'].copy()
scaled_y=scaled_y.astype(int)

# 5.  Hyper parameter tuning

In [31]:
accuracy_all_list=[]
precision_all_list=[]
sensitivity_all_list=[]
specificity_all_list=[]
f1score_all_list=[]
auc_all_list=[]

for i in range(1,11):
    
    #Split the data (split into 80% training data & 20% testing data) (lock seed) 
    x_train,x_test,y_train,y_test=train_test_split(scaled_x,scaled_y,test_size=0.2,random_state=i)

    # Initializing Classifiers
    clf1 = LinearSVC(dual=False,random_state=4)


    # Setting up the parameter grids
    param_grid1 = [{'C': list(range(0, 11))}]

    # K fold cross-validation
    cross_val=KFold(n_splits=5,shuffle=True,random_state=4)
    
    # using gridsearch for hyper-parameter tuning
    gridS_model = GridSearchCV(estimator=clf1,
                                param_grid=param_grid1,
                                scoring='roc_auc',
                                n_jobs=-1,
                                cv=cross_val,
                                verbose=0,
                                refit=True)

    #peforming gridsearch & save each models training result
    gridS_model.fit(x_train, y_train) 
    training_score=gridS_model.best_score_  
    best_parameter=gridS_model.best_params_
    train_model=gridS_model.best_estimator_
    
    
    #print training result
    print('Round',i)
    print('random_state=',i)
    print('Training score:',training_score)
    print('Best Hyper-parameter set:',best_parameter)
    
    # Get model perdiction
    proba=train_model._predict_proba_lr(x_test)[:, 1]
    auc_value = roc_auc_score(y_test, proba)
    fpr, tpr, thresholds = roc_curve(y_test, proba, pos_label=1)
    #caculate Youden's J statistic
    J_score=tpr-fpr
    best_JTH_cutpoint_index=np.argmax(J_score)
    best_JS_threshold=thresholds[best_JTH_cutpoint_index]

    # Calculate performance
    final_prediction=(proba >= best_JS_threshold).astype('int')
    confusion = confusion_matrix(y_test,final_prediction)
    TP=confusion[1,1]
    TN=confusion[0,0]
    FP=confusion[0,1]
    FN=confusion[1,0]
    accuracy=(TP+TN)/(TP+TN+FP+FN)
    sensitivity = TP/(TP+FN)
    specificity = TN/(FP+TN)
    precision=TP/(TP+FP)
    f1score=2*(precision*sensitivity)/(precision+sensitivity)
    

    #print results
    print('Testing results with best threshold')
    print('===================================')
    print('Accuracy:   ',round(accuracy,3))
    print('Precision:  ',round(precision,3))
    print('Sensitivity:',round(sensitivity,3))
    print('Specificity:',round(specificity,3))
    print('F1 score:   ',round(f1score,3))
    print('AUC:        ',round(auc_value,3))
    print('ThresHold:  ',best_JS_threshold)
    print('-----------------------------------')
    print(confusion)
    print('---------------------------------------')
    print('---------------------------------------\n\n')
    
#     #plot ROC fig with exist package module
#     roc_fig=plot_roc_curve(train_model, x_test, y_test)
    
    
    
    accuracy_all=[round(accuracy,3)]
    for a in accuracy_all:
        accuracy_all_list+=[a]
        
    precision_all=[round(precision,3)]
    for a in precision_all:
        precision_all_list+=[a]
    
    sensitivity_all=[round(sensitivity,3)]
    for a in sensitivity_all:
        sensitivity_all_list+=[a]
        
    specificity_all=[round(specificity,3)]
    for a in specificity_all:
        specificity_all_list+=[a]
        
    f1score_all=[round(f1score,3)]
    for a in f1score_all:
        f1score_all_list+=[a]
        
    auc_all=[round(auc_value,3)]
    for a in auc_all:
        auc_all_list+=[a]


best_Accuracy=max(accuracy_all_list)
best_round=accuracy_all_list.index(best_Accuracy)+1
print('Best:',best_Accuracy)
print('Best Round:',best_round)
print('---------------------------------------')
print('Accuracy_mean:',round(np.mean(accuracy_all_list),3),',Accuracy_std:',round(np.std(accuracy_all_list),2))
print('Precision_mean:',round(np.mean(precision_all_list),3),',Precision_std:',round(np.std(precision_all_list),2))
print('Sensitivity_mean:',round(np.mean(sensitivity_all_list),3),',Sensitivity_std:',round(np.std(sensitivity_all_list),2))
print('Specificity_mean:',round(np.mean(specificity_all_list),3),',Specificity_std:',round(np.std(specificity_all_list),2))
print('F1 score_mean:',round(np.mean(f1score_all_list),3),',F1 score_std:',round(np.std(f1score_all_list),2))
print('AUC_mean:',round(np.mean(auc_all_list),3),',AUC_std:',round(np.std(auc_all_list),2))


C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 55.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_classes.py", line 257, in fit
    self.coef_, self.intercept_, self.n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
  File "

Round 1
random_state= 1
Training score: 0.7985375401433352
Best Hyper-parameter set: {'C': 9}
Testing results with best threshold
Accuracy:    0.747
Precision:   0.158
Sensitivity: 0.941
Specificity: 0.737
F1 score:    0.27
AUC:         0.893
ThresHold:   0.3015831660607831
-----------------------------------
[[480 171]
 [  2  32]]
---------------------------------------
---------------------------------------


Round 2
random_state= 2
Training score: 0.8135876781688808
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.685
Precision:   0.159
Sensitivity: 0.909
Specificity: 0.669
F1 score:    0.27
AUC:         0.832
ThresHold:   0.28530470393182905
-----------------------------------
[[429 212]
 [  4  40]]
---------------------------------------
---------------------------------------


Round 3
random_state= 3
Training score: 0.8270784047247142
Best Hyper-parameter set: {'C': 8}
Testing results with best threshold
Accuracy:    0.65
Precision:   0.109


C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 55.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_classes.py", line 257, in fit
    self.coef_, self.intercept_, self.n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
  File "

Round 4
random_state= 4
Training score: 0.8252923196275586
Best Hyper-parameter set: {'C': 4}
Testing results with best threshold
Accuracy:    0.632
Precision:   0.108
Sensitivity: 0.909
Specificity: 0.618
F1 score:    0.192
AUC:         0.79
ThresHold:   0.2857888752636081
-----------------------------------
[[403 249]
 [  3  30]]
---------------------------------------
---------------------------------------


Round 5
random_state= 5
Training score: 0.8196278219380547
Best Hyper-parameter set: {'C': 6}
Testing results with best threshold
Accuracy:    0.674
Precision:   0.121
Sensitivity: 0.833
Specificity: 0.666
F1 score:    0.212
AUC:         0.788
ThresHold:   0.29163989017778325
-----------------------------------
[[432 217]
 [  6  30]]
---------------------------------------
---------------------------------------


Round 6
random_state= 6
Training score: 0.8152853602223914
Best Hyper-parameter set: {'C': 8}
Testing results with best threshold
Accuracy:    0.718
Precision:   0.16

C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 55.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_classes.py", line 257, in fit
    self.coef_, self.intercept_, self.n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
  File "

Round 7
random_state= 7
Training score: 0.813237215839927
Best Hyper-parameter set: {'C': 2}
Testing results with best threshold
Accuracy:    0.806
Precision:   0.142
Sensitivity: 0.778
Specificity: 0.807
F1 score:    0.24
AUC:         0.84
ThresHold:   0.318939710564631
-----------------------------------
[[531 127]
 [  6  21]]
---------------------------------------
---------------------------------------


Round 8
random_state= 8
Training score: 0.8208008998588371
Best Hyper-parameter set: {'C': 1}
Testing results with best threshold
Accuracy:    0.667
Precision:   0.122
Sensitivity: 0.861
Specificity: 0.656
F1 score:    0.214
AUC:         0.797
ThresHold:   0.2906619735739133
-----------------------------------
[[426 223]
 [  5  31]]
---------------------------------------
---------------------------------------


Round 9
random_state= 9
Training score: 0.8212785916106794
Best Hyper-parameter set: {'C': 3}
Testing results with best threshold
Accuracy:    0.657
Precision:   0.118
Se

C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 55.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_classes.py", line 257, in fit
    self.coef_, self.intercept_, self.n_iter_ = _fit_liblinear(
  File "C:\Users\user\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 1186, in _fit_liblinear
    raw_coef_, n_iter_ = liblinear.train_wrap(
  File "

In [25]:
x_train,x_test,y_train,y_test=train_test_split(scaled_x,scaled_y,test_size=0.2,random_state=7)
model=LinearSVC(C=2,dual=False,random_state=4)
model.fit(x_train,y_train)

LinearSVC(C=2, dual=False, random_state=4)